<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Version>1.0.3</Version>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <IlcGenerateMstatFile>true</IlcGenerateMstatFile>
        <IlcGenerateDgmlFile>true</IlcGenerateDgmlFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SnippingToolOcrCore\SnippingToolOcrCore.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ConsoleAppFramework" Version="5.3.4">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="System.Drawing.Common" Version="9.0.1" />
    </ItemGroup>

</Project>
