<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Version>1.0.3</Version>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IlcGenerateMstatFile>true</IlcGenerateMstatFile>
        <IlcGenerateDgmlFile>true</IlcGenerateDgmlFile>
        <UseWindowsForms>true</UseWindowsForms>
        <PublishSingleFile>true</PublishSingleFile>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <SelfContained>true</SelfContained>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SnippingToolOcrCore\SnippingToolOcrCore.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ConsoleAppFramework" Version="5.3.4">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="System.Drawing.Common" Version="9.0.1" />
    </ItemGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.WindowsDesktop.App" />
    </ItemGroup>

    <ItemGroup>
      <None Include="oneocr.dll" CopyToOutputDirectory="PreserveNewest">
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </None>
      <None Include="onnxruntime.dll" CopyToOutputDirectory="PreserveNewest">
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </None>
      <None Include="oneocr.onemodel" CopyToOutputDirectory="PreserveNewest">
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </None>
    </ItemGroup>

</Project>
