name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.4'
      framework:
        description: 'Target framework'
        required: true
        default: 'net9.0-windows'
        type: choice
        options:
          - net9.0-windows
          - net8.0-windows

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: Build SimpleOneOcr
      run: dotnet publish SimpleOneOcr/SimpleOneOcr.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:EnableCompressionInSingleFile=true -f ${{ github.event.inputs.framework }} -o ./publish

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}-${{ github.event.inputs.framework }}
        name: Release v${{ github.event.inputs.version }} (${{ github.event.inputs.framework }})
        draft: false
        prerelease: false
        files: ./publish/*.exe
        token: ${{ secrets.GITHUB_TOKEN }}
